### ISSUE TITLE
Missed conf/market.json

### ISSUE THREAD

**Issue by evgemar** [aira-dao/aira-IoT#1]
Seems like conf/market missed

https://github.com/airalab/aira-IoT/tree/master/docker/market

<img width="437" alt="capture" src="https://user-images.githubusercontent.com/296414/28340085-22bc9dd0-6c17-11e7-9432-5085c18ddb5d.png">

**Comment by akru** [comment]
This file will be created after initiation process by aira web ui.
So may be crash isn't the best behavior.
